# Nome do aplicativo 
spring.application.name=ecommerce-backend

# Caminho da conexão com o banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

# Nome de usuário e senha do banco de dados
spring.datasource.username=louiz    

# Senha do banco de dados
spring.datasource.password=q1w2e3r4

# Classe do driver JDBC para o MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ativa a criação das tabelas do banco de dados a partir das entidades JPA
spring.jpa.hibernate.ddl-auto=create

# Exibe as consultas SQL no console e formata a saída
spring.jpa.show-sql=true

# Formata as consultas SQL exibidas no console
spring.jpa.properties.hibernate.format_sql=true

# Define a plataforma de banco de dados para o Hibernate, neste caso, MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect